title: Velo
description: Documentation for Velo, a Laravel based BaaS.
remote_theme: just-the-docs/just-the-docs

color_scheme: dark

logo: "../public/assets/velo.svg"
logo_alt: "Velo"

search_enabled: true
heading_anchors: true

aux_links:
  "Velo Repository": https://github.com/kevintherm/velo

footer_content: "Copyright &copy; 2026 Velo. All rights reserved."
